Export adapter
container-registry/harbor_upstream pull request #45
Opened 2024-10-21 08:47 UTC by bupd

Thank you for contributing to Harbor!

# Comprehensive Summary of your change

# Issue being fixed
Fixes #(issue)

Please indicate you've done the following:
- [ ] Well Written Title and Summary of the PR
- [ ] Label the PR as needed. "release-note/ignore-for-release, release-note/new-feature, release-note/update, release-note/enhancement, release-note/community, release-note/breaking-change, release-note/docs, release-note/infra, release-note/deprecation"
- [ ] Accepted the DCO. Commits without the DCO will delay acceptance.
- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed in [website repository](https://github.com/goharbor/website).

2024-10-24 21:02 UTC, Vad1mo requested changes

2024-10-24 21:02 UTC, Vad1mo commented on src/controller/replication/flow/stage.go
stage.go should not change, it has an impact on other adapters, preventing them from working.

2024-10-25 20:28 UTC, tpoxa commented on src/controller/replication/flow/stage.go
> +		if policy.DestRegistry.Type == "artifact-list-export" {
I see some debug print statements left in the code. But the most important thing is that such PR won't be accepted by the community of Harbor.  We can't place such a switcher inside of core logic.

2024-10-25 21:02 UTC, Mehul-Kumar-27 commented
There is some issue at the replication at `https://github.com/bupd/harbor.git`, the state file does not appears at the given project after replication.

2024-11-26 15:45 UTC, Vad1mo approved these changes

2024-11-26 15:46 UTC, bupd commented
Update the artifact-list-export to harbor-satellite.
and also look for workarounds for not touching the core logic.

2025-12-28 13:13 UTC, closed without merging